# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Restore Java Keystore File
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" > keystore.asc
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch keystore.asc > app/AndroidStudioSigningKey.jks
        
    - name: Restore google-services.json files
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON_RELEASE }}" > release_google-services.json.asc
        echo "${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}" > debug_google-services.json.asc
        mkdir app/src/release
        mkdir app/src/debug
        gpg -d --passphrase "${{ secrets.GOOGLE_SERVICES_JSON_DEBUG_RELEASE_PASSPHRASE }}" --batch release_google-services.json.asc > app/src/release/google-services.json
        gpg -d --passphrase "${{ secrets.GOOGLE_SERVICES_JSON_DEBUG_RELEASE_PASSPHRASE }}" --batch debug_google-services.json.asc > app/src/debug/google-services.json
    - name: Build Release Apk with Gradle
      run: ./gradlew assembleRelease
    - name: Build Debug Apk with Gradle
      run: ./gradlew assembleDebug
    - name: Build Release Bundle with Gradle 
      run: ./gradlew :app:bundleRelease
    - name: Build Debug Bundle with Gradle
      run: ./gradlew :app:bundleDebug
      
    - name: Get APK files
      uses: actions/upload-artifact@v2
      with:
        name: Get Release apk 
        path: |
          app/build/outputs/apk/release/app-release.apk
          app/build/outputs/apk/debug/app-debug.apk
          app/release/app-release.aab
          app/debug/app-debug.aab
          




